name: aad_oauth_web
description: A flutter oAuth package for Azure Active Directory. Takes code from Earlybyte @ github.com/Earlybyte/aad_oauth and adds web support using hive.
version: 0.1.9
homepage: https://github.com/the03ennis/aad_oauth_web

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_webview_plugin: ^0.3.11
  flutter_secure_storage: ^3.2.0
  path_provider: ^1.6.5
  http: ^0.12.0
  shared_preferences: ^0.5.2
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  get: ^3.2.2


dependency_overrides:
  path: ^1.6.4
  hive_flutter: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
