name: aad_oauth
description: A flutter oAuth package for Azure Active Directory. Takes code from Earlybyte @ github.com/Earlybyte/aad_oauth and adds web support using hive.
version: 0.1.9
homepage: https://github.com/the03ennis/aad_oauth

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_webview_plugin: ^0.3.0+2
  flutter_secure_storage: ^3.2.0
  http: ^0.12.0
  shared_preferences: ^0.5.2
  flutter:
    sdk: flutter
  hive: ^1.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
